config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'active_support/security_utils'
require 'subdomain_routes'
Rails.application.routes.draw do
  use_doorkeeper do
    skip_controllers :applications, :authorized_applications
    # controllers applications: 'agents/authorizations',
    # tokens: 'agents/custom_authorizations'
    # authorizations: 'custom_authorizations',
    #    tokens: 'custom_authorizations',
    #    applications: 'custom_authorizations',
    #    token_info: 'custom_authorizations'
  end

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?

  post '/graphql', to: 'graphql#execute'
  post '/api/graphql', to: 'api/graphql#execute'
  get :widget, to: 'widgets#show', path: '/embed'

  get :show, to: 'api/v1/credentials#show', path: '/api/v1/me'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    # Protect against timing attacks:
    # - See https://codahale.com/a-lesson-in-timing-attacks/
    # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
    # - Use & (do not use &&) so that it doesn't short circuit.
    # - Use digests to stop length information leaking
    ActiveSupport::SecurityUtils.secure_compare(user, ENV['ADMIN_EMAIL']) &
      ActiveSupport::SecurityUtils.secure_compare(password, ENV['ADMIN_PASSWORD'])
  end

  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :agents, controllers: {
    registrations: 'agents/registrations',
    invitations: 'agents/invitations',
    sessions: 'agents/sessions',
    omniauth_callbacks: 'agents/omniauth_callbacks'
  } do
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_agent_session
  end

  resource :oembed, controller: 'oembed', only: :show
  get '/package_iframe/:package' => 'application#package_iframe'
  post '/package_iframe_internal/:package' => 'application#package_iframe_internal'
  post '/dummy_webhook' => 'application#dummy_webhook'

  constraints(SubdomainOrDomain) do
    # TODO, regex ?
    get '/' => 'articles#show'
    get '/:lang' => 'articles#show'
    get '/:lang/collections' => 'articles#show'
    get '/:lang/collections/:id' => 'articles#show'
    get '/:lang/articles/:id' => 'articles#show'
    get '/collections' => 'articles#show'
    get '/collections/:id' => 'articles#show'
    get '/articles/:1/' => 'articles#show'
  end

  root to: 'home#show'
  get '/apps/:app/premailer/:id/' => 'application#preview'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'tester' => 'client_tester#show'
  get 'tester/:id' => 'client_tester#show'
  get 'tester/:id/:id2' => 'client_tester#show'
  get 'tester/:id/:id2/id3' => 'client_tester#show'
  get 'tester/:id/:id2/id3/:id4' => 'client_tester#show'

  get '/' => 'home#show', as: :agents

  scope path: '/api' do
    scope path: '/v1' do
      resources :hooks, only: [:create], controller: 'api/v1/hooks'

      post 'hooks/global/:provider' => 'api/v1/hooks/provider#global_process_event'
      get 'hooks/global/:provider' => 'api/v1/hooks/provider#global_process_event'

      post 'hooks/receiver/:id' => 'api/v1/hooks/provider#process_event'
      get 'hooks/receiver/:id' => 'api/v1/hooks/provider#process_event'

      post 'oauth/callback/:id' => 'api/v1/hooks/provider#oauth'
      get 'oauth/callback/:id' => 'api/v1/hooks/provider#oauth'

      # get 'oauth/:app_key/:provider/:id' => 'api/v1/hooks/provider#oauth'
      # get 'hooks/:app_key/:provider/:id' => 'api/v1/hooks/provider#create'
      # post 'hooks/:app_key/:provider/:id' => 'api/v1/hooks/provider#process_event'

      resources :direct_uploads, only: [:create], controller: 'api/v1/direct_uploads'

      resources :subscription_hooks, only: [:create], controller: 'api/v1/subscription_hooks'
    end
  end

  get '*path', to: 'application#catch_all', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
end

app/views/layouts/_footer.erb
<footer class="footer">
  <div class="container">
    
  </div>
</footer>

app/views/layouts/_header.erb
<div class="header py-4">
  <div class="container">
    <div class="d-flex">

      <a class="header-brand" href="<%= root_url %>">
        Chaskiq
        <!--<img src="./demo/brand/tabler.svg" class="header-brand-img" alt="tabler logo">-->
      </a>

      <div class="d-flex order-lg-2 ml-auto">
        
        <% if current_user.present? %>
          <div class="dropdown">
            <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
              <span class="avatar" style="background-image: url('')"></span>
              <span class="ml-2 d-none d-lg-block">
                <span class="text-default">
                  <%= current_user.email %>
                </span>
                
                  <small class="text-muted d-block mt-1">Administrator</small>
             
              </span>
            </a>

            <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                <a class="dropdown-item" href="#">
                  <i class="dropdown-icon fe fe-log-out"></i>
                  Sign out
                </a>
            </div>
          </div>
        <% end %>

      </div>

      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>
<div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg order-lg-first">

        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          
 
            <li class="nav-item">
              <a class="nav-link" href="">
                <i class="fas fa-newspaper"></i>
                Campaigns
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="">
                <i class="fas fa-address-card"></i>
                Lists
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="">
                <i class="fas fa-object-group"></i>
                Templates
              </a>
            </li>

            <li class="separator"></li>
            
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaskiq App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/png" href="<%= asset_url('favicon.png') %>" sizes="16x16">

    <meta content='True' name='HandheldFriendly'>
    <meta content='320' name='MobileOptimized'>
    <meta name="chaskiq-host" content="<%= ENV['HOST'] %>"/>

    <!--
    <meta content='width=device-width, initial-scale=1' name='viewport'>
    <meta content='width=device-width, initial-scale=1' media='(device-height: 568px)' name='viewport'>
    -->
    <meta
      name="viewport"
      content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
    >
    <!--<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/antd/3.5.4/antd.css">-->

    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.42.0/mapbox-gl.css' rel='stylesheet' />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <script src='https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css' rel='stylesheet' />

    <script> window.chaskiq_cable_url = "<%= ENV['WS'] %>"</script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <%= stylesheet_pack_tag "application" %> 
    <%= javascript_pack_tag 'application' %>
    <!--<link href="https://fonts.googleapis.com/css?family=PT+Sans|Roboto+Mono&display=swap" rel="stylesheet">-->
    <!--<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext" rel="stylesheet">-->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,500,700,800&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class="page" id="main-page">
    </div>

    <% if enabled_subscriptions? %>
      <script src="https://cdn.paddle.com/paddle/paddle.js"></script>
      <script type="text/javascript">
        Paddle.Setup({ vendor: 115475 });
      </script>
    <% end %>

    <% if current_agent.present? and
      support_data = support_app_data and
      support_data.present? %> 

      <script>
        (function(d,t) {
          var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
          g.src="<%=ENV['HOST']%>/embed.js"
          s.parentNode.insertBefore(g,s);
          g.onload=function(){
            new window.ChaskiqMessengerEncrypted({
              domain: "<%= ENV['HOST'] %>",
              ws:  "<%= ENV['WS'] %>",
              app_id: "<%= support_app_data[:app].key %>",
              data: <%= raw support_app_data[:enc] %>
            })
          }
        })(document,"script");
      </script>

    <% end %>
  </body>
</html>

app/views/layouts/articles.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @app.article_settings.site_title %></title>
    <link rel="icon" type="image/png" href="<%= @app.article_settings.logo_url %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="chaskiq-host" content="<%= ENV['HOST'] %>"/>
    <meta content='True' name='HandheldFriendly'>
    <meta content='320' name='MobileOptimized'>
    <!--<meta content='width=device-width, initial-scale=1' name='viewport'>
    <meta content='width=device-width, initial-scale=1' media='(device-height: 568px)' name='viewport'>
    -->
    <meta
      name="viewport"
      content="minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no"
    >

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag "application" %> 

    <link href="https://fonts.googleapis.com/css?family=PT+Sans|Roboto+Mono&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
  
  </head>

  <body>
    <div class="page" id="main-page">
    </div>


    <% if @app.article_settings && @app.article_settings.google_code %>

      <script 
        key="3"
        async 
        src="https://www.googletagmanager.com/gtag/js?id=<%= @app.article_settings.google_code %>"
      >
      </script>

      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', "<%= @app.article_settings.google_code %>" );
      </script>
    <% end %>

    <script>
      (function(d,t) {
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src="<%=@h[:http] +request.env["HTTP_HOST"]%>/embed.js"
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chaskiqMessenger = new window.ChaskiqMessengerEncrypted({
            domain: '<%=@h[:http] +request.env["HTTP_HOST"]%>',
            ws:  '<%= Rails.application.config.action_cable.url %>',
            //lang: "<%= @lang %>",
            data: {},
            app_id: "<%= @app.key %>"
          })
        }
      })(document,"script");
    </script>



  </body>
</html>

app/views/layouts/client.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaskiq CLIENT TEST</title>
    <%= yield :head %>
  </head>

  <body>
    <%= yield :body %>
  </body>
</html>

app/views/layouts/devise.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaskiq</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/tailwindcss@^2.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <% stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
    
    .error, .alert, .notice, .success, .info {padding:0.8em;margin-bottom:1em;text-align: center;}
    .success {background:#e6efc2;color:#264409;}
    .actions{
      margin-top: 2em;
      margin-bottom: 2em;
    }
    
    </style>

  </head>

  <body>
    <div class="page" id="main-page">
        <% flash.each do |key, value| %>
          <div class="m-8 bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
            <span class="block sm:inline"><%= key %> <%= value %></span>
            <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
              <svg class="fill-current h-6 w-6 text-red-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
            </span>
          </div>
        <% end %>
        <div class="mt-6">
          <%= yield %>
        </div>
        
    </div>
  </body>
</html>